# Generated by Django 3.0.6 on 2020-07-30 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='overview',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
