# Generated by Django 3.0.6 on 2020-08-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='authorimg',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='authorname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
