# Generated by Django 3.0.8 on 2020-08-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200803_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='authdesc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
